spring:
  profiles.active: development
  application:
    name: hello-world

server:
  port: 8080

trace-request:
  hibernate:
    hbm2ddl.auto: none
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/trace_request
    user: postgres
    pass: postgres@123

maven:
  version: @pom.version@
  artifactId: @pom.artifactId@
  groupId: @pom.groupId@

ci:
  build.number: @ci.build@
